export const SET_DATABASE='SET_DATABASE';

export const REQUEST_PAGE_PENDING = 'REQUEST_PAGE_PENDING';
export const REQUEST_PAGE_SUCCESS = 'REQUEST_PAGE_SUCCESS';
export const REQUEST_PAGE_FAILED = 'REQUEST_PAGE_FAILED';

export const GET_ACCESS_SUCCESS = 'GET_ACCESS_SUCCESS';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const CATEGORY_CHOICE = 'CATEGORY_CHOICE';

export const ADD_PAGE_SUCCESS = 'ADD_PAGE_SUCCESS';
export const ADD_PAGE_FAILED = 'ADD_PAGE_FAILED';
export const PAGE_ADDED="Your page has been added to our database";

export const DISPLAY_CARD='DISPLAY_CARD';

export const SET_SEARCH_FIELD='SET_SEARCH_FIELD';
export const SET_COUNTRY_FILTER='SET_COUNTRY_FILTER';
export const SET_CATEGORY_FILTER='SET_CATEGORY_FILTER';
export const FILTERS='FILTERS';

export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_PENDING="LOGIN_PENDING";
export const LOGIN_FAILED="LOGIN_FAILED"
export const LOGOUT='LOGOUT';
export const REGISTER='REGISTER';
export const REGISTER_FAILED="REGISTER_FAILED";
// 
export const UPDATE_FAVOURITES="UPDATE_FAVOURITES";
export const UPDATE_USERS_FAVOURITES="UPDATE_USERS_FAVOURITES";
// app
export const ACCESS_TOKEN='EAAMyBcjmzcIBANXIEZCvuWKXI5OMwckVtzlX6B6YlxPUommBxEvmvB5OERvMrtBuJ2k2cJxtxAYZC8W7utdAz91GgnG9XDxlA4dfYkcl13hFnw3BfySx3sTbHpQSSePQQe5aOk94jwl7X9AsqcBDishf13B9UZD';
//test
// export const ACCESS_TOKEN='EAAMyBcjmzcIBAM6Oc0PHxF0ZAPE9yKNcdCID4ihPwSt1ZCW75X8fZBZCN9Wp5moYxr1CWOAqtWCgEKrfAmp4aoHKPukml4kXN6NE1qqsZBr6qV4P75EoE9qZArFZC03ZBMM8x65Fvq1qDXZASbfLWZCU3Jkp8fTTLhVs2TOPPJuSsc3gZDZD';

