export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';

export const REQUEST_PAGE_PENDING = 'REQUEST_PAGE_PENDING';
export const REQUEST_PAGE_SUCCESS = 'REQUEST_PAGE_SUCCESS';
export const REQUEST_PAGE_FAILED = 'REQUEST_PAGE_FAILED';

export const GET_ACCESS_SUCCESS = 'GET_ACCESS_SUCCESS';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const CATEGORY_CHOICE = 'CATEGORY_CHOICE';

export const ADD_PAGE_SUCCESS = 'ADD_PAGE_SUCCESS';
export const ADD_PAGE_FAILED = 'ADD_PAGE_FAILED';

export const DISPLAY_CARD='DISPLAY_CARD';

export const SET_SEARCH_FIELD='SET_SEARCH_FIELD';
export const SET_COUNTRY_FILTER='SET_COUNTRY_FILTER';
export const SET_CATEGORY_FILTER='SET_CATEGORY_FILTER';
export const FILTERS='FILTERS';

export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_PENDING="LOGIN_PENDING";
export const LOGIN_FAILED="LOGIN_FAILED"
export const LOGOUT='LOGOUT';
export const REGISTER='REGISTER';
export const REGISTER_FAILED="REGISTER_FAILED";
//app
//export const ACCESS_TOKEN='EAAMyBcjmzcIBAOy3EktuBUiWSZBYpimyeZBcQfs394edK1tUGhZAqfGLQwMVUjqcZB86hfEFpcDvYRYBPYjvjrSZCk9l8JG8fS5BtVblXx9OzM6HYdDZAIoFoa2rmwnCaZBueeA2gH2DR73ZBZBrzFa0GB5u4yMzzJuuYhrQxeeZC8FAZDZD';
//test
export const ACCESS_TOKEN='EAAHA0tNTMtsBAHUeiZAoMqP90D8ymOcBwLX5292m4SrVToITnlZC1jQ8CP3h1M9JcVr9z6cacvwucjWG9NTvW4KxxlupGAkbYK3iGMVKaiXPIvwHAMQz6epQd7Aas3uP54rTQStedmFY3hIGlibqP04ZBDWtTdIYI13Erk3CwZDZD';

